services:
  backend:
    container_name: backend
    image: minhquan1607/backend:v1.0.0
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./Server:/app
    networks:
      - app-network
    env_file:
      - ./Server/.env

  client-customer:
    container_name: client-customer
    image: minhquan1607/client-customer:v1.0.1
    build:
      context: .
      dockerfile: client-customer/Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://backend:3000
    ports:
      - "3002:80"
    depends_on:
      - backend
    networks:
      - app-network

  client-admin:
    container_name: client-admin
    image: minhquan1607/client-admin:v1.0.1
    build:
      context: .
      dockerfile: client-admin/Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://backend:3000
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
